# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - billpayment-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Repo'yu çek
      - uses: actions/checkout@v4

      # 2️⃣ Azure login
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F8CF8493B05473B9A5B02DD2D844F30 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B9623A0B4F224D0E8BF3C2FDE408E440 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_65B003CC76A5443EB140819C8F852622 }}

      # 3️⃣ Azure App Service'e SOURCE CODE deploy et
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: billpayment-api
          slot-name: Production
          package: .
